# Run this action only for pull requests from this repository
name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'adobe' # replace 'adobe' with repo owner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
      working-directory: test
    - run: npm run lint
    - run: npm test
      working-directory: test
      env:
        CI: true
